version: "3"
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    environment:
      TIMESCALEDB_TELEMETRY: "off"
      POSTGRES_PASSWORD: "test"
      TCK_DB_PASSWORD: "othertest"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
  app:
    environment:
      TCK_DB_PASSWORD: "othertest"
      TCK_DB_LOGIN: "logs"
      TCK_DB_HOST: "timescaledb"
    build: .
    command:
      ["uvicorn", "api.web:app", "--host", "0.0.0.0", "--port", "8181"]
    ports:
      - 8181:8181
    volumes:
      - ./api:/opt/api

volumes:
  db-data:
    driver: local
