version: "3"
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    environment:
      TIMESCALEDB_TELEMETRY: "off"
      POSTGRES_PASSWORD: "test"
      TCK_DB_PASSWORD: "othertest"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - 3000:3000

volumes:
  db-data:
    driver: local
